### ISSUE TITLE
Demolish building gives session expired message.

### ISSUE THREAD

**Issue by icydee** [Kantigen/ka-server#15]
Construct a building, (a water production plant).
Either while building, or after it is built, click the 'demolish'
When the pop-up is shown (do you really want to demolish this building), click 'yes'.
Immediately an exception is raised 'session error'.

**Comment by icydee** [comment]
'session error' usually means that the type of the call has changed (from positional to named) and there is a miss-match.

**Comment by GrooverMD** [comment]
Darin,

Will the Keno Antigen experience have scripting? If so, what scripting, perl, python, etc? I am currently working on the KADE (Keno Antigen Dev Env), and would appreciate some feedback. [😊]

Regards,

Mark (Insidia).

**Comment by dmcbride** [comment]
@GrooverMD - yes, see https://github.com/Kantigen/kac-perl-client for the official perl client.  However, since the protocol will eventually be JSON-over-websocket, which is fundamentally similar to TLE but over different technology, I expect that people who want to write a client in javascript / node won't have any problem.  I would expect that someone proficient in both python and either js or perl or websockets in general would not have a problem scripting KA in python as well.  Existing TLE scripts will _not_ work without significant modification, though many of the concepts will remain unchanged (it will be a porting effort).
