### ISSUE TITLE
ka-server setup

### ISSUE THREAD

**Issue by ghost** [Kantigen/ka-server#21]
Trying to follow these steps:
https://github.com/Kantigen/ka-server/blob/master/info/setup.md 
on Debian 9.6 stable.
On step 7 (Connecting to the Database) I've got error: 
"_Couldn't connect to Docker daemon at http+docker://localhost - is it running? 
If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable._"

**Comment by nataliethistime** [comment]
Hello and thanks for your interest in Keno Antigen. I would assume that you're a former Lacuna player who's found this repo and tried to see what happens?

Unfortunately, whatever the case may be, it's been around three years since anyone has done anything here so I have no idea what is working and what is not. The person most likely to know the answer here would be @dmcbride who I believe was the last to get this stuff running. 

If Darin can't help I would otherwise be unsure as to who can, sadly.

**Comment by dmcbride** [comment]
This does sound a bit more like a docker configuration error. I remember having a lot of docker configuration problems at first, but whether it was this one or other ones, I don't recall.

I would suggest ensuring your docker network is up and running for starters. For example, on my machine, `ifconfig` shows `docker0` as a network. It's this private network that your containers will talk over, and, if it doesn't exist, I would expect an error message similar to the one you got.

**Comment by ghost** [comment]
Retried today and succeded.
Thank you! :)
